import { DM_Sans, Urbanist, Inter, Poppins } from "next/font/google";
import "../app/globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import Providers from "../Provider/Providers";

// Import fonts
const dmSans = DM_Sans({ weight: ["300", "400", "500", "700"], subsets: ["latin"], variable: "--font-dm-sans" });
const urbanist = Urbanist({ weight: ["300", "400", "500", "700"], subsets: ["latin"], variable: "--font-urbanist" });
const inter = Inter({ weight: ["300", "400", "500", "700"], subsets: ["latin"], variable: "--font-inter" });
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Job Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // bg-[#EAECEE]
        className={`${dmSans.variable} ${urbanist.variable} ${poppins.variable} ${inter.variable} antialiased bg-[#ffffff]`}
      >
        <Providers>
        <AntdRegistry>{children}</AntdRegistry>
        </Providers>
      </body>
    </html>
  );
}
